AWSTemplateFormatVersion: 2010-09-09

# Create an S3 bucket with AES256 encryption, and which rejects unencrypted PUT's.
Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${AWS::StackName}-s3bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: RequiredSecureTransport
            Action:
              - 's3:*'
            Effect: Deny
            Resource: !Sub arn:aws:s3:::${Bucket}/*
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': false
          - Sid: S3Encryption
            Action:
              - 's3:PutObject'
            Effect: Deny
            Resource: !Sub arn:aws:s3:::${Bucket}/*
            Principal: '*'
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': true

Outputs:
  S3Bucket:
    Description: S3Bucket
    Value:
      Ref: Bucket
    Export:
      Name: !Sub ${AWS::StackName}
