AWSTemplateFormatVersion: 2010-09-09

Resources:
  RdsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${AWS::StackName}
      Description: The private DB secrets
      SecretString: '{"username":"admin","password":"administrator"}'
