AWSTemplateFormatVersion: 2010-09-09

Resources:
  WorkflowRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowCallFunctions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:app-serverless-lambda-retriever
                  - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:app-serverless-lambda-exporter

  WorflowStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${AWS::StackName}
      DefinitionS3Location:
        Bucket: !ImportValue app-serverless-s3-bucket
        Key: workflow-definition.asl.json
      DefinitionSubstitutions:
        RetrieverFunction: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:app-serverless-lambda-retriever
        ExporterFunction: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:app-serverless-lambda-exporter
      RoleArn: !GetAtt WorkflowRole.Arn
